export interface ErrorCodeDef {
  readonly code: string
  readonly category: string
  readonly httpStatus: number
  readonly isRetryable: boolean
  readonly refundsCredits: boolean
}

function def(
  code: string,
  category: string,
  httpStatus: number,
  isRetryable = false,
  refundsCredits = false,
): ErrorCodeDef {
  return { code, category, httpStatus, isRetryable, refundsCredits }
}

export const ERROR_CODES = {
  AUTH_TOKEN_INVALID: def('AUTH_TOKEN_INVALID', 'AUTH', 401),
  AUTH_TOKEN_EXPIRED: def('AUTH_TOKEN_EXPIRED', 'AUTH', 401),
  AUTH_TOKEN_REVOKED: def('AUTH_TOKEN_REVOKED', 'AUTH', 401),
  AUTH_INSUFFICIENT_PERMISSIONS: def('AUTH_INSUFFICIENT_PERMISSIONS', 'AUTH', 403),
  AUTH_WORKSPACE_SUSPENDED: def('AUTH_WORKSPACE_SUSPENDED', 'AUTH', 403),
  AUTH_ORGANIZATION_SUSPENDED: def('AUTH_ORGANIZATION_SUSPENDED', 'AUTH', 403),
  AUTH_MFA_REQUIRED: def('AUTH_MFA_REQUIRED', 'AUTH', 403),
  AUTH_OAUTH_CONSENT_REQUIRED: def('AUTH_OAUTH_CONSENT_REQUIRED', 'AUTH', 403),

  BILLING_INSUFFICIENT_CREDITS: def('BILLING_INSUFFICIENT_CREDITS', 'BILLING', 402),
  BILLING_BUDGET_EXCEEDED: def('BILLING_BUDGET_EXCEEDED', 'BILLING', 402),
  BILLING_PLAN_LIMIT_REACHED: def('BILLING_PLAN_LIMIT_REACHED', 'BILLING', 402),
  BILLING_PAYMENT_FAILED: def('BILLING_PAYMENT_FAILED', 'BILLING', 402),
  BILLING_PAYMENT_PENDING: def('BILLING_PAYMENT_PENDING', 'BILLING', 409, true),
  BILLING_SUBSCRIPTION_EXPIRED: def('BILLING_SUBSCRIPTION_EXPIRED', 'BILLING', 402),

  MCP_SERVER_NOT_FOUND: def('MCP_SERVER_NOT_FOUND', 'MCP', 404),
  MCP_SERVER_NOT_ACTIVE: def('MCP_SERVER_NOT_ACTIVE', 'MCP', 409),
  MCP_TOOL_NOT_FOUND: def('MCP_TOOL_NOT_FOUND', 'MCP', 404),
  MCP_TOOL_DISABLED: def('MCP_TOOL_DISABLED', 'MCP', 409),
  MCP_TOOL_PERMISSION_DENIED: def('MCP_TOOL_PERMISSION_DENIED', 'MCP', 403),
  MCP_TOOL_INPUT_INVALID: def('MCP_TOOL_INPUT_INVALID', 'MCP', 422),
  MCP_TOOL_REQUIRES_APPROVAL: def('MCP_TOOL_REQUIRES_APPROVAL', 'MCP', 202),
  MCP_SQL_STATEMENT_REJECTED: def('MCP_SQL_STATEMENT_REJECTED', 'MCP', 422),
  MCP_CONNECTOR_UNREACHABLE: def('MCP_CONNECTOR_UNREACHABLE', 'MCP', 502, true, true),
  MCP_CONNECTOR_AUTH_FAILED: def('MCP_CONNECTOR_AUTH_FAILED', 'MCP', 502),
  MCP_CONNECTOR_TIMEOUT: def('MCP_CONNECTOR_TIMEOUT', 'MCP', 504, true, true),
  MCP_CIRCUIT_BREAKER_OPEN: def('MCP_CIRCUIT_BREAKER_OPEN', 'MCP', 503, true),
  MCP_BRIDGE_OFFLINE: def('MCP_BRIDGE_OFFLINE', 'MCP', 503, true),

  AGENT_NOT_FOUND: def('AGENT_NOT_FOUND', 'AGENT', 404),
  AGENT_NOT_ACTIVE: def('AGENT_NOT_ACTIVE', 'AGENT', 409),
  AGENT_ALREADY_RUNNING: def('AGENT_ALREADY_RUNNING', 'AGENT', 409, true),
  AGENT_MAX_ITERATIONS_REACHED: def('AGENT_MAX_ITERATIONS_REACHED', 'AGENT', 422),
  AGENT_TIMEOUT: def('AGENT_TIMEOUT', 'AGENT', 408),
  AGENT_BUDGET_EXCEEDED: def('AGENT_BUDGET_EXCEEDED', 'AGENT', 402),
  AGENT_TOOL_LOOP_DETECTED: def('AGENT_TOOL_LOOP_DETECTED', 'AGENT', 422),
  AGENT_SELF_REFERENCE_DENIED: def('AGENT_SELF_REFERENCE_DENIED', 'AGENT', 403),
  AGENT_NESTING_TOO_DEEP: def('AGENT_NESTING_TOO_DEEP', 'AGENT', 422),
  AGENT_OUTSIDE_ALLOWED_HOURS: def('AGENT_OUTSIDE_ALLOWED_HOURS', 'AGENT', 409),
  AGENT_AWAITING_APPROVAL: def('AGENT_AWAITING_APPROVAL', 'AGENT', 202),

  LLM_PROVIDER_UNAVAILABLE: def('LLM_PROVIDER_UNAVAILABLE', 'LLM', 503, true, true),
  LLM_PROVIDER_RATE_LIMITED: def('LLM_PROVIDER_RATE_LIMITED', 'LLM', 429, true),
  LLM_CONTEXT_TOO_LONG: def('LLM_CONTEXT_TOO_LONG', 'LLM', 422),
  LLM_CONTENT_FILTERED: def('LLM_CONTENT_FILTERED', 'LLM', 422),
  LLM_MODEL_NOT_AVAILABLE: def('LLM_MODEL_NOT_AVAILABLE', 'LLM', 404),
  LLM_MODEL_BYOK_ONLY: def('LLM_MODEL_BYOK_ONLY', 'LLM', 403),
  LLM_BYOK_KEY_INVALID: def('LLM_BYOK_KEY_INVALID', 'LLM', 400),

  MARKET_ITEM_INCOMPATIBLE: def('MARKET_ITEM_INCOMPATIBLE', 'MARKET', 409),
  MARKET_ENTITLEMENT_REQUIRED: def('MARKET_ENTITLEMENT_REQUIRED', 'MARKET', 402),

  WEBHOOK_SIGNATURE_INVALID: def('WEBHOOK_SIGNATURE_INVALID', 'WEBHOOK', 401),

  IDEMPOTENCY_KEY_REUSED: def('IDEMPOTENCY_KEY_REUSED', 'IDEMPOTENCY', 409),

  PLATFORM_RATE_LIMIT: def('PLATFORM_RATE_LIMIT', 'PLATFORM', 429, true),
  PLATFORM_MAINTENANCE: def('PLATFORM_MAINTENANCE', 'PLATFORM', 503, true),
  PLATFORM_INTERNAL_ERROR: def('PLATFORM_INTERNAL_ERROR', 'PLATFORM', 500, true, true),
  PLATFORM_FEATURE_NOT_AVAILABLE: def('PLATFORM_FEATURE_NOT_AVAILABLE', 'PLATFORM', 403),
  PLATFORM_FEATURE_DISABLED: def('PLATFORM_FEATURE_DISABLED', 'PLATFORM', 403),
  PLATFORM_RESOURCE_NOT_FOUND: def('PLATFORM_RESOURCE_NOT_FOUND', 'PLATFORM', 404),
  PLATFORM_VALIDATION_ERROR: def('PLATFORM_VALIDATION_ERROR', 'PLATFORM', 422),
  PLATFORM_CONFLICT: def('PLATFORM_CONFLICT', 'PLATFORM', 409),

  GUARDRAIL_INPUT_BLOCKED: def('GUARDRAIL_INPUT_BLOCKED', 'GUARDRAIL', 422),
  GUARDRAIL_PROMPT_ATTACK: def('GUARDRAIL_PROMPT_ATTACK', 'GUARDRAIL', 422),
  GUARDRAIL_ACTION_BLOCKED: def('GUARDRAIL_ACTION_BLOCKED', 'GUARDRAIL', 403),
  GUARDRAIL_OUTPUT_BLOCKED: def('GUARDRAIL_OUTPUT_BLOCKED', 'GUARDRAIL', 422),
  EMERGENCY_STOP_ACTIVE: def('EMERGENCY_STOP_ACTIVE', 'GUARDRAIL', 503),
} as const satisfies Record<string, ErrorCodeDef>

export type ErrorCode = keyof typeof ERROR_CODES

export type ErrorCategory =
  | 'AUTH'
  | 'BILLING'
  | 'MCP'
  | 'AGENT'
  | 'LLM'
  | 'MARKET'
  | 'WEBHOOK'
  | 'IDEMPOTENCY'
  | 'PLATFORM'
  | 'GUARDRAIL'

export function getErrorCode(code: string): ErrorCodeDef | undefined {
  if (!Object.hasOwn(ERROR_CODES, code)) return undefined
  return (ERROR_CODES as Record<string, ErrorCodeDef>)[code]
}

export function isRetryable(code: ErrorCode): boolean {
  return ERROR_CODES[code].isRetryable
}
