export const GLOSSARY = {
  fr: {
    simple: {
      connector: 'système connecté',
      mcp_server: 'accès IA',
      tool: 'action',
      agent: 'assistant automatique',
      capability: 'fonction IA',
      workspace: 'espace de travail',
      environment: 'mode',
      run: 'exécution',
      prompt: 'consigne',
      token: 'unité de texte',
      api_key: "clé d'accès",
      webhook: 'notification automatique',
      guardrail: 'règles de sécurité',
      routing_profile: 'profil',
      credit: 'crédit',
      budget: 'budget',
      approval: 'à valider',
      byok: 'votre propre clé IA',
    },
    technical: {
      connector: 'connecteur',
      mcp_server: 'serveur MCP',
      tool: 'outil',
      agent: 'agent',
      capability: 'capacité',
      workspace: 'workspace',
      environment: 'environnement',
      run: 'run',
      prompt: 'prompt',
      token: 'token',
      api_key: 'clé API',
      webhook: 'webhook',
      guardrail: 'garde-fou',
      routing_profile: 'profil de routage',
      credit: 'crédit',
      budget: 'budget',
      approval: 'approbation requise',
      byok: 'BYOK',
    },
  },
  en: {
    simple: {
      connector: 'connected system',
      mcp_server: 'AI access point',
      tool: 'action',
      agent: 'automated assistant',
      capability: 'AI function',
      workspace: 'workspace',
      environment: 'mode',
      run: 'execution',
      prompt: 'instruction',
      token: 'text unit',
      api_key: 'access key',
      webhook: 'automatic notification',
      guardrail: 'safety rule',
      routing_profile: 'profile',
      credit: 'credit',
      budget: 'budget',
      approval: 'pending approval',
      byok: 'your own AI key',
    },
    technical: {
      connector: 'connector',
      mcp_server: 'MCP server',
      tool: 'tool',
      agent: 'agent',
      capability: 'capability',
      workspace: 'workspace',
      environment: 'environment',
      run: 'run',
      prompt: 'prompt',
      token: 'token',
      api_key: 'API key',
      webhook: 'webhook',
      guardrail: 'guardrail',
      routing_profile: 'routing profile',
      credit: 'credit',
      budget: 'budget',
      approval: 'approval required',
      byok: 'BYOK',
    },
  },
} as const

export type GlossaryTerm = keyof typeof GLOSSARY.fr.simple
export type GlossaryMode = 'simple' | 'technical'
export type Locale = 'fr' | 'en'

export function t(term: GlossaryTerm, locale: Locale, mode: GlossaryMode): string {
  return GLOSSARY[locale][mode][term]
}
